@startuml 6-1
left to right direction
title プリンターのステートマシン図

[*] -right-> 待機中 : 電源を入れる

待機中 --> 印刷中 : 印刷開始
印刷中 --> 待機中 : 印刷完了
印刷中 --> 用紙無し : 用紙切れ
用紙無し --> 印刷中 : 用紙を補充
[*] <-right- 待機中 : 電源を切る



@enduml
