@startuml 商品検索
hide footbox
Actor "<u>:会員</u>" as me
participant ":商品検索画面" as se <<boundary>>
participant ":商品検索コントローラ" as co  <<control>>
participant "<u>:商品</u>" as go <<entity>>
participant "<u>:商品カテゴリ</u>" as ca <<entity>>

activate me
    me -> se: 商品情報を検索
    activate se
        se -> co: 商品情報検索要求
        activate co
            co -> go: 商品情報を検索
            activate go
            go --> co: 商品情報を返す
            deactivate go
            co -> ca: 商品カテゴリを検索
            activate ca
            ca --> co: 商品カテゴリを返す
            deactivate ca
            co --> se: 検索結果を返す
        deactivate co
        se -> se: 商品情報表示
        deactivate se
deactivate me
@enduml
