@startuml
!define AWESOME https://raw.githubusercontent.com/awesometic/plantuml-icon-font-sprites/v1.4/sprites

left to right direction

actor 利用者 as user
actor 管理者 as admin

rectangle 病院管理システム {
  usecase (予約する) as UC1
  usecase (ログイン) as UC2
  usecase (ログアウト) as UC3
  usecase (予約を確認する) as UC4
  usecase (予約を変更する) as UC5
  usecase (予約をキャンセルする) as UC6

  user --> UC1
  user --> UC2
  user --> UC3
  user --> UC4
  user --> UC5
  user --> UC6

  admin --> UC2
  admin --> UC3
  admin --> UC4
  admin --> UC5
  admin --> UC6
}
@enduml